In [13]:
f = open('agencies.txt', 'r')

#Read all lines
lines = f.readlines()

#Process lines
for l in lines:
    #print(l[:-1])
    print(l[:-1].split(' ')[0])

f.close()

Federal
Central
The
Housing
The
The


In [1]:
#Process file manually 
f = open('authors.txt', 'r')

author_lines = f.readlines()

print('{0:20s}{1:20s}'.format('Name','Email'))
#Skip 3 row
author_lines = author_lines[3:]
for line in author_lines:
    items = line.split('<')
    name = items[0][:-1]
    email = items[-1][:-2]
    print('{0:30s}{1:20s}'.format(name,email))

f.close()

Name                Email               
Paul Bakaus                   paul.bakaus@gmail.com
Richard Worth                 rdworth@gmail.com   
Yehuda Katz                   wycats@gmail.com    
Sean Catchpole                sean@sunsean.com    
John Resig                    jeresig@gmail.com   
Tane Piper                    piper.tane@gmail.com
Dmitri Gaskin                 dmitrig01@gmail.com 
Klaus Hartl                   klaus.hartl@gmail.com
Stefan Petre                  stefan.petre@gmail.com
Gilles van den Hoven          gilles@webunity.nl  
Micheil Bryan Smith           micheil@brandedcode.com
Jörn Zaefferer               joern.zaefferer@gmail.com
Marc Grabanski                m@marcgrabanski.com 
Keith Wood                    kbwood@iinet.com.au 
Brandon Aaron                 brandon.aaron@gmail.com
Scott González               scott.gonzalez@gmail.com
Eduardo Lundgren              eduardolundgren@gmail.com
Aaron Eisenberger             aaronchi@gmail.com  
Joan Piedra      

In [3]:
import numpy as np
falling_data = np.loadtxt('falling.txt', skiprows=5)
print(falling_data)

[[  0.    0.  180.    3.5]
 [  1.    0.5 185.    4.5]
 [  2.    0.7 192.    5.2]]


In [4]:
data_point = falling_data[:, 0]
time_data = falling_data[:, 1]
print(data_point)
print(time_data)

[0. 1. 2.]
[0.  0.5 0.7]


In [5]:
data_point, times, heights, errors = np.loadtxt('falling.txt', skiprows=5, unpack=True)
print(data_point, times)

[0. 1. 2.] [0.  0.5 0.7]


In [6]:
# Exercise: Read gradebook.txt
grades = np.loadtxt('gradebook.txt', dtype=str, skiprows=7, delimiter='\t')
print(grades)

# Read to columns
# Print student name, ID, grade of passed student (grade >= 4)  

[['huonglmgbh17538' 'huonglmgbh17538@fpt.edu.vn' 'GBH17538'
  'Le Minh Huong' '6.5']
 ['nambpgch16025' 'nambpgch16025@fpt.edu.vn' 'GCH16025' 'Bui Phuong Nam'
  '0']
 ['datntgch16336' 'datntgch16336@fpt.edu.vn' 'GCH16336' 'Nguyen The Dat'
  '6.5']
 ['thangpmgch16388' 'thangpmgch16388@fpt.edu.vn' 'GCH16388'
  'Pham Minh Thang' '6.5']
 ['tungddgch16573' 'tungddgch16573@fpt.edu.vn' 'GCH16573' 'Do Duy Tung'
  '6.5']]


In [12]:
# read to columns
IDs, names,stdgrades = np.loadtxt('gradebook.txt', dtype=str, skiprows=7, delimiter='\t',
                                    unpack=True, usecols=(2,3,4))
print('{0:20s}{1:20s}{2:5s}'.format('ID','Name','Grade'))

# print student name, ID grade of padded students(grade > 4)
for i in range(len(IDs)):
    if float (stdgrades[i]) >=4.0:
        print('{0:10s}{1:20s}{2:5s}'.format(IDs[i],names[i], stdgrades[i]))

ID                  Name                Grade
GBH17538  Le Minh Huong       6.5  
GCH16336  Nguyen The Dat      6.5  
GCH16388  Pham Minh Thang     6.5  
GCH16573  Do Duy Tung         6.5  


In [7]:
import csv

grades = []

f = open('gradebook.csv', 'r')
for row in csv.reader(f, delimiter=','):
    grades.append(row)

print(grades)
grades = grades[1:]
passed_students = [row for row in grades if float(row[-1]) >= 4.5]

print('Passed students')
print('{0:10s}{1:20s}{2:5s}'.format('ID', 'Name', 'Grade'))
for row in passed_students:
    print('{0:10s}{1:20s}{2:>5s}'.format(row[2], row[3], row[4]))
f.close()


[['Login', 'Email', 'Code', 'Name', 'Grade'], ['huonglmgbh17538', 'huonglmgbh17538@fpt.edu.vn', 'GBH17538', 'Le Minh Huong', '6.5'], ['nambpgch16025', 'nambpgch16025@fpt.edu.vn', 'GCH16025', 'Bui Phuong Nam', '0'], ['datntgch16336', 'datntgch16336@fpt.edu.vn', 'GCH16336', 'Nguyen The Dat', '6.5'], ['thangpmgch16388', 'thangpmgch16388@fpt.edu.vn', 'GCH16388', 'Pham Minh Thang', '6.5'], ['tungddgch16573', 'tungddgch16573@fpt.edu.vn', 'GCH16573', 'Do Duy Tung', '6.5']]
Passed students
ID        Name                Grade
GBH17538  Le Minh Huong         6.5
GCH16336  Nguyen The Dat        6.5
GCH16388  Pham Minh Thang       6.5
GCH16573  Do Duy Tung           6.5


In [ ]:
import csv

grades = []

f = open('gradebook.csv', 'r')
for row in csv.reader(f, delimiter=','):
    grades.append(row)

print(grades)
grades = grades[1:]
passed_students = [row for row in grades if float(row[-1]) >= 4.5]

print('Passed students')
print('{0:10s}{1:20s}{2:5s}'.format('ID', 'Name', 'Grade'))
for row in passed_students:
    print('{0:10s}{1:20s}{2:>5s}'.format(row[2], row[3], row[4]))
f.close()
