In [1]:
# Using boolean indexing to clean data
import numpy as np
names = np.array(['Trung', 'Linh', '', 'Hoang', ''])
# Filter empty names
empty_names = names[names=='']
print(len(empty_names))
# Cleaning empty names
names[names==''] = 'An'
print(names)

2
['Trung' 'Linh' 'An' 'Hoang' 'An']


In [6]:
import numpy as np
# Create array of 10 integers from 0 to 20
#1
a = np.linspace(0, 20, 10, endpoint=False, dtype=int)
print(a)

#2
b = np.arange(0, 20, 2)
print(b)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
#Create array of 133 numbers from 1 to 1000
import numpy as np
n = np.arange(1, 1000, (1000-1)/133)
print(n[:10])

m, step = np.linspace(1, 1000, 133, endpoint=False, retstep= True)
print(b[:10])
print(step)

[ 1.          8.5112782  16.02255639 23.53383459 31.04511278 38.55639098
 46.06766917 53.57894737 61.09022556 68.60150376]
[ 0  2  4  6  8 10 12 14 16 18]
7.511278195488722


In [37]:
#4
numbers = np.random.randint(0, 100, 20)
print(numbers)
evens = numbers[numbers%2==0]
sorted_evens = np.sort(evens)
print(evens, sorted_evens, sep= 'n')
#c1: sorted (convert ve array)
#c2: np.sort
#c3: call method sort


[17 59 55 47 42 62 11 70 37 33 57  5 30  2 37 35 90  8 20 36]
[42 62 70 30  2 90  8 20 36]n[ 2  8 20 30 36 42 62 70 90]


In [38]:
sorted_odds = np.sort(numbers[numbers%2==1])
print(sorted_odds)

[ 5 11 17 33 35 37 37 47 55 57 59]


In [39]:
numbers = np.concatenate((sorted_evens, sorted_odds))
print(numbers)

[ 2  8 20 30 36 42 62 70 90  5 11 17 33 35 37 37 47 55 57 59]


In [42]:
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2]) 


In [44]:
distances = y[1:] - y[:-1]
times = t[1:] - t[:-1]
v = distances/times
print(v)

[ 2.65306122  7.25490196 11.8        13.79310345 20.85106383 17.38461538]


In [45]:
#a
names = np.array(['John', ''])
empty_names = names[names=='']
print(len(empty_names))
names[names==''] = 'Doe'
print(names)

1
['John' 'Doe']


In [52]:
#b
ages = np.array([-1, 4, 45, 38, 100])
ages[ages<0] = 0
ages[ages>150] = 150
print(ages)




[  0   4  45  38 100]


In [54]:
#print('Min ages:', min(ages))
print("Min ages:", min(ages))

Min ages: 0
