In [4]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#Slicing
print(arr2d[3], arr2d[-2])
print(arr2d[:, 2])
print(arr2d[1:4, 3])
print(arr2d[1:5, 2:4]) #print(arr2d[1:, 2:4])


NameError: name 'arr2d' is not defined

In [8]:
m = np.ones((8, 8), dtype=int)
m[1:7, 1:7] = 0
print(m)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [10]:
m = np.zeros((8, 8), dtype=int)
#print(m)
#C1
m[0] = 1
m[-1] = 1
m[:, 0] = 1
m[:, -1] = 1
print(m)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [11]:
m = np.random.randint(10, 100, (8, 8))
print(m)


[[11 92 21 49 60 85 27 45]
 [96 27 28 67 37 76 10 86]
 [13 23 20 22 14 17 48 98]
 [24 28 87 95 53 67 14 13]
 [85 29 23 87 98 41 68 19]
 [19 46 56 31 96 58 12 82]
 [22 57 67 23 29 66 80 63]
 [97 61 71 23 40 85 55 57]]


In [1]:
grades = {'Nam':7.0, 'Bac':6.5, 'Son':5.0, 'Ha':9.5, 'Le':10.0, 'Trung':4.0}

In [3]:
gpas = grades.values()
print(gpas)
max_gpa = max(gpas)
print('Max gpa =', max_gpa)

dict_values([7.0, 6.5, 5.0, 9.5, 10.0, 4.0])
Max gpa = 10.0


In [4]:
print(list(grades.items()))

[('Nam', 7.0), ('Bac', 6.5), ('Son', 5.0), ('Ha', 9.5), ('Le', 10.0), ('Trung', 4.0)]


In [5]:
for s, gpa in grades.items():
    if gpa == max_gpa:
        print('Best student:', s)

Best student: Le


In [6]:
name = 'Bac'
print('GPA of {0} = {1}'.format(name, grades.get(name)))
print('GPA of {0} = {1}'.format(name, grades[name]))

GPA of Bac = 6.5
GPA of Bac = 6.5


In [7]:
print('Best student:', max(grades, key=grades.get))

Best student: Le


In [8]:
import numpy as np
mean_gpa = np.mean(list(gpas))
print('Mean GPA =', mean_gpa )

Mean GPA = 7.0


In [9]:
sum_gpa = 0
for s, gpa in grades.items():
    sum_gpa += gpa
print('Mean GPA =', sum_gpa / len(grades))

Mean GPA = 7.0


In [15]:
print(grades)
name = input('Enter name:')
print('grades{0} = {1}'.format(name, grades[name]))


{'Nam': 7.0, 'Bac': 6.5, 'Son': 5.0, 'Ha': 9.5, 'Le': 10.0, 'Trung': 4.0}
gradesNam = 7.0


In [16]:
# for (int i = 1; i < 20; i = i+2)
for i in range(1, 20, 2):
    print(i, end=' ')

1 3 5 7 9 11 13 15 17 19 

In [18]:
# Print multiplication table
n = int(input('Enter n: '))

In [19]:
for i in range(1, 11):
    print('{0:2d} x {1:2d} = {2:2d}'.format(i, n, i*n))

 1 x  4 =  4
 2 x  4 =  8
 3 x  4 = 12
 4 x  4 = 16
 5 x  4 = 20
 6 x  4 = 24
 7 x  4 = 28
 8 x  4 = 32
 9 x  4 = 36
10 x  4 = 40


In [20]:
names = list(grades.keys())
print(names)

['Nam', 'Bac', 'Son', 'Ha', 'Le', 'Trung']


In [21]:
for n in names:
    print(n)

Nam
Bac
Son
Ha
Le
Trung


In [22]:
i = 1
for n in names:
    print('{0}.{1}'.format(i, n))
    i += 1

1.Nam
2.Bac
3.Son
4.Ha
5.Le
6.Trung


In [23]:
for i, n in enumerate(names):
    print('{0}.{1}'.format(i, n))
    i += 1

0.Nam
1.Bac
2.Son
3.Ha
4.Le
5.Trung


In [24]:
for i, n in enumerate(names):
    print('{0}.{1}'.format(i+1, n))

1.Nam
2.Bac
3.Son
4.Ha
5.Le
6.Trung


In [25]:
print(list(enumerate(names)))

[(0, 'Nam'), (1, 'Bac'), (2, 'Son'), (3, 'Ha'), (4, 'Le'), (5, 'Trung')]
